export const texts = {
  english: {
    chartmenu: 'Price Chart',
    homemenu: 'Home',
    exchangemenu: 'Exchange',
    trademenu: 'Trade Bitcoin',
    supportmenu: 'Support',
    loginmenu: 'Login',
    logoutmenu: 'Logout',
    languagemenu: 'Language',
    englishmenu: 'English',
    chinesemenu: 'Chinese',
    wallet: 'Connect Wallet',
    charttitle: 'Premium Access',
    chartcontent1: 'This feature is exclusive for users to have account!',
    chartcontent2: 'Please registe account to have access to useful products on LinuCoin ecosystem:',
    chartcontent3: 'Multichart',
    chartcontent4: 'And more tools coming soon!',
    chartcontent5: 'Chart',
    chartcontent6: 'Keep tracking of all your coins in the same place.',
    chartcontent7: 'You can generate up to 2 charts and track real-time currency prices in addition to your price history.',
    chartcontent8: 'Go',
    chartcontent9: 'BNB is a cryptocurrency that can be used to trade and pay fees on the Binance cryptocurrency exchange.',
    chartcontent10: 'Binance USD (BUSD) is a type of cryptocurrency that is referred to as a stablecoin.',
    chartcontent11: 'CAKE is the delicious token that powers the PancakeSwap ecosystem.',
    logintitle: 'Login',
    loginsubtitle: 'Sign In to your account',
    logincontent1: 'Enter Username',
    logincontent2: 'Enter Password',
    logincontent3: 'Login',
    logincontent4: 'Forgot password?',
    logincontent5: 'Sign up',
    logincontent6: 'Click below button to signup with LeaderInu.',
    logincontent7: 'Register Now!',
    signuptitle: 'Create Account',
    signupsubtitle: 'Sign Up to your account',
    signupcontent1: 'Enter Username',
    signupcontent2: 'Enter Email',
    signupcontent3: 'Enter FirstName',
    signupcontent4: 'Enter LastName',
    signupcontent5: 'Enter Password',
    signupcontent6: 'Enter Confirm Password',
    signupcontent7: 'Create Account',
    signupcontent8: 'Back to Login?',
    emailtitle: 'Email Verification using OPT',
    emailcontent1: 'Enter OPT Number',
    emailcontent2: 'Submit',
    forgottitle: 'Forgot Password',
    forgotcontent1: 'Enter Email',
    forgotcontent2: 'Submit',
    forgotcontent3: 'Go to Login?',
    exchangecontent1: 'Enter the coin amount',
    exchangecontent2: 'Enter the coin price',
    exchangecontent3: 'coin value',
    exchangecontent4: 'Create Wallet'
  },
  chinese: {
    chartmenu: '价格图表',
    homemenu: '关于',
    exchangemenu: '交换',
    trademenu: '交易比特币',
    supportmenu: '支持',
    loginmenu: '登录',
    logoutmenu: '登出',
    languagemenu: '语言',
    englishmenu: '英语',
    chinesemenu: '中文',
    wallet: '连接钱包',
    charttitle: '高级访问',
    chartcontent1: '此功能是用户拥有账号的专属功能！',
    chartcontent2: '请注册一个帐户以访问 LinuCoin 生态系统中的有用产品：',
    chartcontent3: '多个图表',
    chartcontent4: '更多工具即将推出！',
    chartcontent5: '图表',
    chartcontent6: '在一个地方跟踪您的所有硬币。',
    chartcontent7: '除了价格历史，您最多可以生成 2 个图表并跟踪实时货币价格.',
    chartcontent8: '去',
    chartcontent9: 'BNB 是一种加密货币，可用于在 Binance 加密货币交易所进行交易和支付费用.',
    chartcontent10: 'Binance USD (BUSD) 是一种被称为稳定币的加密货币.',
    chartcontent11: 'CAKE 是为 PancakeSwap 生态系统提供动力的美味代币.',
    logintitle: '登录',
    loginsubtitle: '登录到您的帐户',
    logincontent1: '输入你的用户名',
    logincontent2: '输入密码',
    logincontent3: '登录',
    logincontent4: '你忘记密码了吗？',
    logincontent5: '登记',
    logincontent6: '点击下面的按钮注册LeaderInu.',
    logincontent7: '现在注册！',
    signuptitle: '创建帐户',
    signupsubtitle: '注册您的帐户',
    signupcontent1: '输入你的用户名',
    signupcontent2: '输入电子邮件',
    signupcontent3: '输入名字',
    signupcontent4: '输入姓氏',
    signupcontent5: '输入密码',
    signupcontent6: '输入确认密码.',
    signupcontent7: '创建帐户',
    signupcontent8: '回到登入？',
    emailtitle: '使用 OPT 进行电子邮件验证',
    emailcontent1: '输入选择号码',
    emailcontent2: '提交',
    forgottitle: '忘记密码',
    forgotcontent1: '输入电子邮件',
    forgotcontent2: '提交',
    forgotcontent3: '登录？',
    exchangecontent1: '输入硬币数量',
    exchangecontent2: '输入硬币价格',
    exchangecontent3: '硬币价值',
    exchangecontent4: '创建钱包'
  }
}